sudo: false
language: python
python:
  - "2.7"

notifications:
  email: false

virtualenv:
  system_site_packages: true

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - export PATH=$HOME/miniconda:$PATH
  - conda update --yes conda

install:
  - export PATH=./src/qinfer:$PATH
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose pip cython
  - pip install -r requirements.txt
  - cd ./src/qinfer

script:
  - nosetests --with-coverage --cover-package=qinfer qinfer

after_success:
  - coveralls