sudo: false
language: python
python:
  - "2.7"

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - export PATH=./src/qinfer:$PATH
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose pip cython
  - pip install -r requirements.txt
  - python setup.py install
  - cd ./src/qinfer

script:
  - nosetests --with-coverage --cover-package=qinfer qinfer

after_success:
  - coveralls